import React from 'react';
import { StyleSheet, View } from 'react-native';
import { Button as PaperButton, Dialog, Portal, Text as PaperText } from 'react-native-paper';
import { useMutation } from '@tanstack/react-query';
import nutritionApi, { LogMealPayload } from '@/services/nutritionApi';
import { useSnackbar, Button, Text } from '@/components';
import { spacing } from '@/utils';
import { MealEntry, MealLogResponse, MealPlanHistoryItem } from '@/types/mealPlan';

interface Props {
  visible: boolean;
  meal: MealEntry | null;
  dayNumber?: number | null;
  plan: MealPlanHistoryItem | null;
  onDismiss: () => void;
  onLogged?: () => void;
  userId?: string;
}

const MealDetailModal = ({ visible, meal, dayNumber, plan, onDismiss, onLogged, userId }: Props) => {
  const { showSnackbar } = useSnackbar();

  const logMealMutation = useMutation<MealLogResponse, Error, LogMealPayload>({
    mutationFn: (payload: LogMealPayload) => {
      if (!userId) {
        return Promise.reject(new Error('未找到用户信息，请稍后重试'));
      }
      return nutritionApi.logMeal(userId, payload);
    },
    onSuccess: () => {
      showSnackbar('Meal logged', { variant: 'success' });
      onDismiss();
      onLogged?.();
    },
    onError: (error: unknown) => {
      const message = error instanceof Error ? error.message : 'Failed to log meal';
      showSnackbar(message, { variant: 'error' });
    },
  });

  if (!meal) {
    return null;
  }

  const handleLogMeal = () => {
    if (!userId) {
      showSnackbar('缺少用户信息，无法记录', { variant: 'error' });
      return;
    }
    logMealMutation.mutate({
      mealPlanId: plan?.id,
      mealDay: dayNumber ?? undefined,
      mealType: meal.mealType,
      recipeId: meal.recipeId ?? undefined,
      recipeName: meal.recipeName ?? undefined,
      calories: meal.calories ?? undefined,
      protein: meal.protein ?? undefined,
      carbs: meal.carbs ?? undefined,
      fat: meal.fat ?? undefined,
    });
  };

  return (
    <Portal>
      <Dialog visible={visible} onDismiss={onDismiss} style={styles.dialog}>
        <Dialog.Title>{meal.recipeName ?? meal.mealType}</Dialog.Title>
        <Dialog.Content>
          <View style={styles.macrosRow}>
            <MacroItem label="Calories" value={meal.calories ?? '--'} unit="kcal" />
            <MacroItem label="Protein" value={meal.protein ?? '--'} unit="g" />
            <MacroItem label="Carbs" value={meal.carbs ?? '--'} unit="g" />
            <MacroItem label="Fat" value={meal.fat ?? '--'} unit="g" />
          </View>
          {plan?.source && (
            <Text variant="caption" style={{ opacity: 0.7, marginTop: spacing.md }}>
              Generated by {plan.source} · Day {dayNumber}
            </Text>
          )}
        </Dialog.Content>
        <Dialog.Actions>
          <Button title="Close" variant="ghost" onPress={onDismiss} />
          <PaperButton
            mode="contained"
            onPress={handleLogMeal}
            loading={logMealMutation.isPending}
            disabled={logMealMutation.isPending || !userId}
          >
            标记已吃
          </PaperButton>
        </Dialog.Actions>
      </Dialog>
    </Portal>
  );
};

const MacroItem = ({ label, value, unit }: { label: string; value: number | string; unit: string }) => (
  <View style={styles.macroItem}>
    <PaperText variant="labelSmall" style={{ opacity: 0.7 }}>{label}</PaperText>
    <PaperText variant="titleMedium">{value}</PaperText>
    <PaperText variant="bodySmall" style={{ opacity: 0.7 }}>{unit}</PaperText>
  </View>
);

const styles = StyleSheet.create({
  dialog: {
    borderRadius: 16,
  },
  macrosRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  macroItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
});

export default MealDetailModal;
