spring:
  application:
    name: fitness-app
  profiles:
    default: dev
  main:
    allow-bean-definition-overriding: true

app:
  youtube:
    api-key: ${YOUTUBE_API_KEY:}
    quota:
      warnings-enabled: true
  spoonacular:
    api-key: ${SPOONACULAR_API_KEY:}
  seed:
    enabled: ${APP_SEED_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
  health:
    redis:
      enabled: true

logging:
  level:
    com.fitnessapp.backend: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fitness_mvp}
    username: ${SPRING_DATASOURCE_USERNAME:fitnessuser}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Using 'update' instead of 'validate' to handle schema evolution gracefully
      # In production, switch to 'validate' and rely on Flyway migrations only
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoint:
    health:
      probes:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: never

server:
  port: ${SERVER_PORT:8080}









