# Production profile configuration for AWS deployment

# Use real Redis cache in production
spring.cache.type=redis

# AWS ElastiCache Redis endpoint (update with your cluster host)
spring.data.redis.host=master.aura-redis.rz4l3i.apse2.cache.amazonaws.com
spring.data.redis.port=6379

# Optional: enable if your ElastiCache cluster requires an auth token and TLS
spring.data.redis.password=sy760317zy040113
spring.data.redis.ssl.enabled=true

# Reasonable timeout when talking to cloud-hosted Redis
spring.data.redis.timeout=2000


# Google OAuth 
spring.security.oauth2.client.registration.google.client-id=113023901864-63dojacud95051e1grii61s93l1bjqf2.apps.googleusercontent.com